#!/bin/bash
# Submission script for Hercules2
#SBATCH --time=20:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=8192 #16GB
#SBATCH --partition=hmem
#
#SBATCH --mail-user=surabhi.ranavat@ulb.be
#SBATCH --mail-type=ALL
#
#SBATCH --output=bwa_log.txt

module load releases/2021a
module load BWA/0.7.17-GCC-10.3.0

cd /CECI/proj/eeg/hardy_lab/Pericopsis/trimmed_seq/plastome/
export OMP_NUM_THREADS=32
export MKL_NUM_THREADS=32

echo "Job started on $(date)"

bwa index Pericopsis_elata_plastome.fasta
##for looping through PE files

for f1 in *_R1_001.fastq.gz

do
  f2="${f1%_R1_001.fastq.gz}_R2_001.fastq.gz"
    bwa mem -M -t 32 Pericopsis_elata_plastome.fasta $f1 $f2 > $f1.sam
done

echo "Job ended on $(date)"
