#!/bin/bash
# Submission script for Hercules2
#SBATCH --job-name=samtools_sort_plastome
#SBATCH --time=07:00:00 # days-hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=8192 #16GB
#SBATCH --partition=hmem
#
#SBATCH --mail-user=surabhi.ranavat@ulb.be
#SBATCH --mail-type=ALL
#
#SBATCH --comment=Pericopsis
#
#SBATCH --output=samtools_sort_plastome_log.txt


module load releases/2022b
module load SAMtools/1.17-GCC-12.2.0

cd /CECI/proj/eeg/hardy_lab/Pericopsis/trimmed_seq/plastome

export OMP_NUM_THREADS=16
export MKL_NUM_THREADS=16

echo "Job started on $(date)"

for f1 in *_R1_001.sub.fq.gz.sam
do
  samtools view -@ 16 -Sb $f1 | samtools sort -o $f1.bam
done

echo "Job ended on $(date)"
